.npmignore
bower.json

This includes a bower.json file so as to publish it to the repository

Completed Bower Support

---

index.js
test.js

Typographer

---

README.md
index.js
package.json
test.js

Code blocks

---

index.js

**Note:** last char in `token.info` should be `}`
Fixes #15

support any block with {}-curlies in `token.info`

---

.travis.yml
package.json

Fenced code blocks fixed in markdown-it 7.0.1.

Bump markdown-it dep

---

index.js
test.js

Ordered lists

---

README.md
index.js
package.json
test.js

```md
- item
- nested
- item 2
{.green}
```
should give
```html
<ul class="green">
<li>item
<ul>
<li>nested</li>
</ul>
</li>
<li>item 2</li>
</ul>
```
not
```html
<ul>
<li>item
<ul class="green">
<li>nested</li>
</ul>
</li>
<li>item 2</li>
</ul>
```

Nested lists

---

package-lock.json
package.json
patterns.js
test.js

Fixes https://github.com/arve0/markdown-it-implicit-figures/issues/18

Implicit figures

---

patterns.js
test.js

avoid "end of block" applying to code_inline

---

index.js
test.js

support multiple "inline nesting 0" in same paragraph

---

test.js
utils.js

if `{attr}` → length must be 3 or more
if `{.class}` or `{#id}` → length must be 4 or more

hasCurly checks length of string more carefully

---

README.md
index.js
markdown-it-attrs.browser.js
patterns.js
test.js
utils.js

Configure Delimiter 

---

patterns.js
test.js

support horizontal rule <hr> --- {#id}

---

.vscode/launch.json
debug.js
index.js
patterns.js
test.js
utils.js

support delimiters with length > 1

---

test.js
utils.js

allow = in values

---

test.js
utils.js

allow dot in class names

---

index.js
test.js

only override options that are set

---

package-lock.json
package.json
utils.js

markdown-it ^9.0.0 compatibility

---

patterns.js
test.js

Fix ~ correct application of trailing 'attr-like' strings within items

---

README.md

... following up to [#102](https://github.com/arve0/markdown-it-attrs/issues/102)

Add note to the README about span styling using markdown-it-bracketed-spans

---

package-lock.json
package.json
patterns.js
test.js

Related issue https://github.com/waylonflinn/markdown-it-katex/issues/24

fix: resolve conflict with markdown-it-katex plugin

---

package-lock.json
package.json

confirming that all tests pass (closes #139)

allow for markdown-it 13 and up
